# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Run a single simulation of (S1) in Domingues, Kuijper et al 
#' @param kappa strength of density-dependence
#' @returns A \code{data.frame} that contains the various frequencies
#' @export
#' @rawNamespace importFrom(Rcpp, sourceCpp);useDynLib("CRISPRhitchhike");
CRISPRhh <- function(kappa = 0.001) {
    .Call(`_CRISPRhitchhike_CRISPRhh`, kappa)
}

